version: '3'
services:
  django:
    image: python:3.7
    volumes:
      - .:/code/
    ports:
      - 5000:8000
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /code
    command: >
      bash -c "pip install -r requirements.txt 
      && python manage.py runserver 0.0.0.0:8000"
