# Generated by Django 4.0.3 on 2022-03-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category_user_course_created_at_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
