# Generated by Django 4.0.3 on 2022-03-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='created_at',
            new_name='voted_at',
        ),
    ]
