# Generated by Django 4.0.3 on 2022-04-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='added_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.user'),
        ),
    ]
