name: Deploy
on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: ssh
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.HOST_S0 }}
        USERNAME: ${{ secrets.USERNAME_S0 }}
        PORT: ${{ secrets.PORT_S0 }}
        KEY: ${{ secrets.SSH_KEY_S0 }}
      with:
        script: "cd /home/ubuntu/Git/django-project && git pull && sudo docker-compose -f docker-compose.yml up -d"
